### ISSUE TITLE
Jitter issues related to timing interpolation/extrapolation

### ISSUE THREAD

**Issue by renaudbedard** [renaudbedard/fez-1.12-issues#103]
This is an issue I'll keep around to track the visual problems I caused when adding interpolation/extrapolation to fix the timestep=17ms thing... (#101)
- [x] General jitter at 60hz
- [x] Stars jitter
- [x] When Gomez jumps away from a vine, for a split second he looks wrong
- [x] Block lifting/manipulation (rotation/throwing) has visual and gameplay glitches
- [x] Split-up cube wireframe collector jitters when Gomez moves
- [x] Rotation intro into the world map jitters
- [x] Black Gomez hexahedron filling and drumming cutscenes are broken
- [x] Menucube animation jitters
- [x] Sky layers and cloud parallax jitters
- [x] Moving platforms with Gomez standing on them (like RAILS or LAVA) cause jitter
- [x] Lifted block (bomb or block) jitters (minor)

**Comment by Gyoo** [comment]
I can confirm Gomez is jittering, but it felt like he was jittering most of the time for me. I'll dig into it further.

**Comment by renaudbedard** [comment]
I fixed the jiterring @ 60hz that you were likely experiencing, the problems of the original post still remain though. (workin' on it)

**Comment by renaudbedard** [comment]
Pushed a fix for the split up cube collector & trails for this... one down, four to go!

**Comment by flibitijibibo** [comment]
Got the WorldMap along with other menu-related interpolations (MenuCube, etc).

**Comment by renaudbedard** [comment]
32-bit end cutscene should be jitter-free as well! #progress

**Comment by vrubleg** [comment]
Animation of appearance of the inventory cube is not smooth in v1.12. It seems that such jitter affects this effect also. There is also one another difference: background jumps to the left-top corner for 2-3 pixels just before blurring effect. v1.11 doesn't have such glitch, as I can see.

Does it worth to create a new issue or it will be enough to mention it here?

**Comment by flibitijibibo** [comment]
It sounds like you're one version behind... the latest version fixes both the background positioning as well as the menu interpolation. What does your changelog look like?

**Comment by vrubleg** [comment]
It looks like this:

```
1.12 BETA CHANGES
-----------------

[2016]

12/07 - Fixed possible soft-lock when changing to first-person view in front of a tombstone, valve or timeswitch
12/07 - Fixed regression that caused a visual "pop" of faraway planes following a perspective transition
12/07 - Fixed jittering issues in world map and 32-bit end cutscene
...
```

**Comment by flibitijibibo** [comment]
The best thing I can see for the blur is that there's a possible half-pixel offset that we need to remove. As for the inventory cube, we adjusted the Interpolate routines to run on the draw interval, and I can't reproduce the jitter there. Can you get jitter to happen when shifting the cube left/right?

**Comment by vrubleg** [comment]
Does my part of changelog mean that I have the latest version?

Maybe it's not a jitter. But this animation seem a little bit weird for me. It seems like the cube has some (barely visible) "vibration" during "fly in" animation. Maybe I have this feeling because of noticeable "jump" of the background just before the animation.

BTW, the very first frame of animation with cube shows wrong side. The animation starts from the Treasure Maps side, but the first frame shows the Artifacts side for some reason. Maybe initial position is calculated by one formula, but animation uses another formula for transition. It's almost unnoticeable, so it's not a problem.

Animation of shifting left/right seems ok, but this animation is not so fast, maybe this is why it is harder to notice the jitter here. I'm a little bit sleepy now, so maybe tomorrow morning I'll see it :)

**Comment by renaudbedard** [comment]
Here's how the animation looks like at 120hz, there's a few problems that are obvious : 

![menucube](https://cloud.githubusercontent.com/assets/251134/16826075/42194112-4948-11e6-9050-1cd409dc84d5.gif)
- First frame is fully blurred for some reason
- Half-texel (or more) offset of blurred background
- Text jitters into position
- Even the rotation of the cube doesn't appear fully smooth, it jerks upwards in some frames

I'll investigate!

**Comment by renaudbedard** [comment]
OK I was able to find and fix all issues described above :)

> BTW, the very first frame of animation with cube shows wrong side. The animation starts from the Treasure Maps side, but the first frame shows the Artifacts side for some reason.

I wasn't able to see this problem though, it doesn't appear in my frame-by-frame breakdowns. Maybe I fixed it while I was fixing something else? See if you have the problem with the newest build.

**Comment by vrubleg** [comment]
> Even the rotation of the cube doesn't appear fully smooth, it jerks upwards in some frames

It is exactly what I had meant :) Now it works even better than it was in the v1.11. Thank you.

> BTW, the very first frame of animation with cube shows wrong side. The animation starts from the Treasure Maps side, but the first frame shows the Artifacts side for some reason.

I was wrong about it. I have used the ApiTrace to see it in slow-motion. It had seemed to me that the Artifacts side blinks for a frame just because these artifacts http://veg.by/z/2016-07-14-09-24-29-f6ce5cf7.jpg are brighter than the other stuff, and this side of cube is hidden too quickly, so it seems like these artifacts just blink for a frame before the animation. But it is not true, it's just an illusion of blinking.

GL Retrace "slow motion" video of the first three openings of the inventory cube: https://www.youtube.com/watch?v=pEcQJnF98OM.

You can see that the first opening of the cube has noticeable lag (many initial frames of the animation are skipped). The second and all other times there are no such problem. It seems, that the game uses lazy loading of the 3D models of the cube and artifacts. Actually, it's not annoying because it happens only one time.

> I wasn't able to see this problem though, it doesn't appear in my frame-by-frame breakdowns.

Your GIF shows a little bit different animation in comparison to what I see on my system. Your animation starts from the very bottom place. Initial top position is much higher in my case, it is just a little bit lower than the center of the screen. You can see it on my video or using ApiTrace http://veg.by/files/temp/fez-trace.7z.

**Comment by vrubleg** [comment]
I have seen my retrace in slow-motion, and it seems that I'm wrong about "The next frame jumps to the Treasure Maps side (without animation)", there is some different strange thing. I'm uploading a video with demonstration, it will add it to this message in 10 minutes.

**Comment by renaudbedard** [comment]
You're right about the lazy-loading; I'll leave that as-is, I don't think it's a big issue.

Pretty strange that the start position of the cube is different on our machines... I'll take a look.

**Comment by vrubleg** [comment]
For my taste, my version of the starting position looks better :)

I've googled any other video of the inventory cube and have found this one: https://youtu.be/HKVZANqGRv8?t=6s. In this video, the cube starts from the same position as on my PC. BTW, the video shows some other weird glitch of this cube.

**Comment by renaudbedard** [comment]
Ooookay, false alarm (sorta). The "slide from below" effect of the inventory open transition only occurs when you're in a camera-locking volume (there's one in that mine level I was testing in) and appears to be a problem from the stock game. It's fixed now. :)

The other bug in the video (FRACTAL level) is already fixed, not sure if it's a 1.12 fix or before that though.

**Comment by renaudbedard** [comment]
Fixed sky layer and cloud jitters.
That only leaves the moving platforms, which are worse than I thought at 60hz. At 120hz it looks like mechanical jitter, but at 60hz it jerks around randomly and looks quite off... I'll take a closer look.

**Comment by renaudbedard** [comment]
I tried disabling player interpolation if you're on a moving platform, this partly worked but there's still a jerk upwards/downwards at 60hz when the frame is skipped by the update logic... so not good enough.

I'm trying to do velocity extrapolation on moving platforms to fix that properly but it's not a trivial task. Update order is pretty sensitive, and I don't want to tank performance.

**Comment by renaudbedard** [comment]
Still fighting against moving platforms. I have interpolation in place and it seems to do its job, but I'm still getting a 1-frame jitter when the update doesn't run, despite that the perceptual velocity of everything is constant. It's really confusing and I guess I just need to dig deeper...

One other issue is that in the lava level, even if I do fix it for Gomez + camera + moving platform, I'll still get a jitter for the lava surface unless I also interpolate it. X(

**Comment by vrubleg** [comment]
I believe you can do it! It will be awesome =)

**Comment by renaudbedard** [comment]
Heeeey good news! I think I fixed everything. :)
The problem I had with interpolated platforms was not due to platforms, but rather to the camera not following Gomez's interpolated position correctly. After fixing camera tracking, everything's silky smooth!

I had to make some changes to clean all that up which may introduce more issues. I tested areas that I think would be sensitive and fixed some of them along the way, but it's not impossible that more crop up.
I'll push a build tomorrow (too late to push an update today, I'm worried that I'd push a broken build), and let you know so we can test.

**Comment by renaudbedard** [comment]
Did another minor fix with carried triles, now it's ready for testing! Builds are pushed for Windows (both branches), please let me know if something broke.

**Comment by flibitijibibo** [comment]
Linux/Mac builds have also been pushed to fna-unstable. Will try to do another run tomorrow afternoon.

**Comment by renaudbedard** [comment]
Tentatively closing! If more issues crop up, I'll reopen.
