### ISSUE TITLE
Wrong position after rotating when Gomez stays at the edge of some platforms

### ISSUE THREAD

**Issue by vrubleg** [renaudbedard/fez-1.12-issues#117]
Very easy to reproduce:
https://youtu.be/o8RoWWX4k6Y?t=27s (sorry for bad quality).

Not significant, just for the collection =)

**Comment by renaudbedard** [comment]
It actually is pretty significant, and it's a regression caused from fixing another bug where the Z position of Gomez would change unexpectedly when the player is sandwiched between two columns, like in WALL_HOLE :

![image](https://cloud.githubusercontent.com/assets/251134/17759926/98d00364-64c9-11e6-993d-efb19ee72588.png)

My fix caused Gomez to fall down in a bunch of places in nature levels as well, and some area felt a lot harder to traverse.
I reevaluated my fix and found a solution that covers the initial case I was trying to solve (Gomez's Z position never changing unless the player decides to, or a wall forces Gomez forwards), and not cause additional issues.

It's risky to make another physics fix so late in the patch dev cycle but I think it's the right choice.

**Comment by vrubleg** [comment]
@renaudbedard, it doesn't fall now, but in this case the camera rotates around a wrong position, where Gomez were falling in previous versions. It looks weird.

It seems that the game gets position of Gomez for camera rotation, next it moves Gomez itself to a platform (Z position), next it starts rotation (old Gomez position is used as the center).

**Comment by renaudbedard** [comment]
I think I just fixed it, but the issue was pretty minor in my test cases to begin with... can you see if the latest update makes it any better?

Note : there is also a change (in yesterday's fix) where Gomez visually "snaps" to a different horizontal position in this situation, to prevent issues where Gomez would penetrate level geometry after a bunch of rotations in alcoves like this. I muuuuch prefer having a slight visual pop than putting Gomez in a position that makes gameplay confusing or broken, so I'll keep it that way.

**Comment by vrubleg** [comment]
Now it is better. It is still noticeable that Gomez changes its position before rotating, but it is not significant.

But there is some other problem. Try to enter First Person View [here](http://veg.by/z/2016-08-18-15-56-51-47509de8.png). As the result you will see that there is no platform under Gomez. I don't know how it have to look like in this case. Maybe initial problem doesn't have to be considered as a bug, I don't know. As far as I remember, I hadn't encountered it during normal gameplay.

**Comment by renaudbedard** [comment]
The initial problem definitely was a bug, I had removed some code that solved the issue in all prior versions, so I had to reenable it.

The first-person view "floating" impression is not something I'll fix, however. Gomez is essentially floating in that state so that his head is still visible, so first-person view shows the truth. :)

Closing!
