### ISSUE TITLE
Hi-DPI support for macOS

### ISSUE THREAD

**Issue by renaudbedard** [renaudbedard/fez-1.12-issues#142]
The current build of FEZ 1.12 does not take into account Retina screens on Mac, and presents the game at half resolution whichever resolution you choose.

**Comment by flibitijibibo** [comment]
More specifically, despite the display being 2880x1800, the actual drawable viewport is 1440x900. So in FULLSCREEN_DESKTOP, for example, the window size as well as the drawable size is considered the latter resolution, while a HiDPI mode would allow the drawable space to be the former resolution.

Enabling it is simple, you add SDL_WINDOW_ALLOW_HIGHDPI to the CreateWindow flags and ensure that NSHighResolutionCapable is set to YES in Info.plist.

The difficult part is basically everything else.

The main problem is that XNA never considered HiDPI as something that might be enabled, so there's no easy way to have a window _and_ drawable size that works in the way you'd expect. FNA's faux-backbuffer trick works for the current spec, but that's something we explicitly ask for - the problem with HiDPI is that, if it were enabled by default, the resolution of the game would forcibly be doubled at all times, introducing a considerable performance hit.

A possible fix would be to introduce an "FNA_GRAPHICS_ENABLE_HIDPI" environment variable, which would add the flag and ensure that the SDL hint is set correctly, and from there you'd be on your own to ensure that the PresentationParameters.BackBufferWidth/Height and SDL _drawable_ size (rather than _window_ size) are compared correctly to ensure that faux-backbuffers are still made at the right time. If it's false or unset, we stick with the current behavior. If it was added as an in-game option, it would require a restart to allow a proper CreateWindow call to occur.

**Comment by renaudbedard** [comment]
Wrote the initial implementation in my local FNA repo, it seems to work but needs cleanup/testing. Should probably test HiDPI in Windows 10 as well to see if it works.

**Comment by flibitijibibo** [comment]
The feature will be available in the next update. The option is available as "highDPI" in the Settings file and as a command line argument, `--attempt-highdpi`.

Part of why it's called "attempt" and why it's not in the menus right now is because high-DPI turns out to be EXTREMELY finicky to work with. It can only be done on startup, is not guaranteed to work (so you can't assume it's there beforehand and by the time you've made it it's too late to assign correct defaults in places like the Settings file), and of course it has the performance drop. By default it's off, mainly for the latter reason and because the desktop resolution provided by the OS is always the "simulated" res and not the actual display resolution, so it's easier to, for example, default to low-DPI 1440x900 and have it at least look okay by normal standards, rather than enabling high-DPI 1440x900 (instead of 2880x1800 which is what it should be) and having it look greasy and also laggy. People who want it to look better can enable it and know that the resolution needs to be changed to the correct drawable size without the first impression getting wrecked (and odds are if they even know what this is they'll know what they're doing).

**Comment by renaudbedard** [comment]
Now added as a menu option in Video Settings on macOS. Windows HiDPI is not a thing in SDL2 so that stayed as-is.

So to be clear : no need to put the `--attempt-highdpi` option, though that does still exist and forces the game to at least try. In normal circumstances, toggle the menu option and restart the game (as instructed).

**Comment by renaudbedard** [comment]
Currently only available in the "experimental" branch (password : "therebedragons") because other problems forced me to revert the default branch for now.
