### ISSUE TITLE
Deformed Resolutions

### ISSUE THREAD

**Issue by Gimlao** [renaudbedard/fez-1.12-issues#15]
1366x768 doesn't look like other 16:9 resolutions :

https://dl.dropboxusercontent.com/u/12308005/Jeux/Fez/screens/1280x720.png
» https://dl.dropboxusercontent.com/u/12308005/Jeux/Fez/screens/1366x768.png
https://dl.dropboxusercontent.com/u/12308005/Jeux/Fez/screens/1600x900.png
https://dl.dropboxusercontent.com/u/12308005/Jeux/Fez/screens/1920x1080.png

May be because 1366:768 = 1,778645833333333 instead of 1,777777777777778 ?

Then, non 16:9 resolutions are deformed and can draw the UI out of the screen :

https://dl.dropboxusercontent.com/u/12308005/Jeux/Fez/screens/1280x960.png
https://dl.dropboxusercontent.com/u/12308005/Jeux/Fez/screens/1280x1024.png
https://dl.dropboxusercontent.com/u/12308005/Jeux/Fez/screens/1400x1050.png
https://dl.dropboxusercontent.com/u/12308005/Jeux/Fez/screens/1600x1024.png

**Comment by Gimlao** [comment]
The map is also affeced, only in 1366x768 :

https://dl.dropboxusercontent.com/u/12308005/Jeux/Fez/screens/1366x768_Map.png

**Comment by Yauxo** [comment]
Might be related to this, the FEZ-Logo is sometimes deformed and too big in the credits http://puu.sh/lGrrC/98c526a51a.png

Tested on with bugged results (all window mode): 
1280x768
1280x800
1280x960
1280x1024
1360x768
1360x1024
1400x1050
1440x900
1600x900 (this one also had a messed up border http://puu.sh/lGrFB/d772256112.png and off-center selection http://puu.sh/lGrHu/9187d3219a.png)
1680x1050

**Comment by flibitijibibo** [comment]
All of the issues noted so far have been resolved in revision control; the test build should be updated for users soon.

**Comment by Gimlao** [comment]
@Yauxo What's the resolution of your desktop ?

Please note that, if you select a windowed resolution equal or bigger than your desktop, everything will be messed up, because of the window borders.

For example, my desktop resolution is 1920x1080.
If I select 1920x1080 in windowed mode, the game will render at 1916x1053.

Hopefully, borderless mode is here to fix that. :3

1600x900 is fine. :3

[Edit] Little mistake, you were talking about 1680x1050 in the parenthesis, not 1600x900. ^^;;;

**Comment by flibitijibibo** [comment]
Most of these issues were actually the result of saturating the view scale for resolutions _just_ above 1280x720 and for resolutions with aspect ratios wider than 16:9. The constant value we were using to move some elements up and down would then be off by a handful of pixels since the scale wasn't tied to the vertical factor like it was before (this FEZ Friday will be me whining about this for a little while).

If we find any more issues like these, it'll probably be for the same reason. Just gotta find them all...

**Comment by Yauxo** [comment]
@Gimlao Im using 1920x1080 as well, in case you guys still need that information.

**Comment by Gimlao** [comment]
I was thinking about something that could help any 16:9 resolution to look exactly the same : 

Using 1280x720 in Fullscreen mode will scale the game to the desktop resolution, with some nice filter (very subtle blurry effect). So, 1366x768 / 1600x900 / 1920x1080 could be actually be 2560x1440 (1280x720 x 2) but downscaled with that same nice filter. :3

1280x720
https://dl.dropboxusercontent.com/u/12308005/Jeux/Fez/screens/720_Game.png
https://dl.dropboxusercontent.com/u/12308005/Jeux/Fez/screens/720_Pause.png

1366x768
https://dl.dropboxusercontent.com/u/12308005/Jeux/Fez/screens/768_Game.png
https://dl.dropboxusercontent.com/u/12308005/Jeux/Fez/screens/768_Pause.png

1600x900
https://dl.dropboxusercontent.com/u/12308005/Jeux/Fez/screens/900_Game.png
https://dl.dropboxusercontent.com/u/12308005/Jeux/Fez/screens/900_Pause.png

1920x1080
https://dl.dropboxusercontent.com/u/12308005/Jeux/Fez/screens/1080_Game.png
https://dl.dropboxusercontent.com/u/12308005/Jeux/Fez/screens/1080_Pause.png

_Simply using Paint Shop Pro to illustrate that any 16:9 resolution could look the same. =p_

1440p downscaled should be less blurry than 720p upscaled, but 720p upscaled could help for computers having problems running the game in higher resolutions than 720p.

**Comment by renaudbedard** [comment]
This issue is tracked in the private github repo, so it's in progress (somewhat).
Ethan or I will let you know how this progresses! Thanks.

**Comment by Gimlao** [comment]
Can I request a keyboard shortcut to switch between Fullscreen and Windowed mode ?

Something like "F", "F11" or the well known "Alt + Enter". :3

**Comment by flibitijibibo** [comment]
Will add it to my list for tomorrow!

**Comment by flibitijibibo** [comment]
The Alt-Enter toggle is in revision control and should show up in the next update. One issue that may show up is that the video settings menu will not update the window mode string when you do the alt-enter _inside_ the video settings menu, but if you're in that menu do you really need to do this...?

**Comment by flibitijibibo** [comment]
Going to sit down and deal with the even integer resolutions this week. If not downscaled resolutions it'll be a return to the letterboxes to center the lower-res image into the frame.

**Comment by flibitijibibo** [comment]
The downscaling looked pretty crummy, so I've added an even integer viewport option to the game. This will show up in the next update in the form of a config option; we'll probably add it in-game when we clean up the screen mode option (window/borderlesswindow/fullscreen).

Unlike the old letterboxing, however, we actually still use the window's aspect ratio, so a 1680x1050 window will still render as 1280x800 rather than 1280x720, so you'll still get whatever FOV you had without the integer scaling.

This should deal with the last problem found in this issue!

**Comment by renaudbedard** [comment]
I tried the downscaling myself and found it pretty acceptable... so I'm planning to add it as an option. Or perhaps even the default for 16:9 resolutions that aren't perfect multiples of 720p?

**2560x1440 downsampled to 1920x1080**
![1080](https://cloud.githubusercontent.com/assets/251134/12254565/131d683c-b8b8-11e5-9e61-13febef7f4bd.png)

**2560x1440 downsampled to 1366x768**
![1366](https://cloud.githubusercontent.com/assets/251134/12254568/2b92a29c-b8b8-11e5-86f6-809b9411178f.png)

Another view of 1366x768 in a small zoom level (eyes get a bit garbled)
![image](https://cloud.githubusercontent.com/assets/251134/12254747/1e9d08d2-b8ba-11e5-8f6c-d1b25603bf14.png)

Menu 1px-wide lines get faded a bit in 1366x768, too
![image](https://cloud.githubusercontent.com/assets/251134/12254762/51ad6406-b8ba-11e5-8ed8-908faeb1987b.png)

So we propose 2 sets of options : 
- Screen mode : Windowed, Borderless Window, Fullscreen
- Scale mode : Pixel-perfect, Locked Aspect, Supersampling

_Pixel-perfect_ is what Ethan describes above : only allow scaling if it's integer, so even 1080p will pillarbox and letterbox down to 720p.
_Locked Aspect_ is the behavior of the game right now, with bad pixel scaling if need be. The view scaling steps will be by 0.5 multiples of 720p so you get a mostly pixel perfect 1080p experience (like in 1.11).
_Supersampling_ will downscale from the next higher multiple of 720p. 

For non-16:9 (16:10, 21:9, 4:3, etc. etc.) resolutions, I'd still push for letterboxing so that there's no more vertical space than intended (it usually causes cutscene/UI issues)... but I could be convinced otherwise. I'm just not sure what's worth fighting for.

**Comment by flibitijibibo** [comment]
The scale mode has been implemented in revision control and should be available in the next update as a config option. FullAspect is the default, with PixelPerfect and Supersampled as possible options. The aspect ratio is still maintained in all scaling modes.

**Comment by renaudbedard** [comment]
To keep you guys up to date, and to make it sound like I'm doing Real Work on this (which I am, but just very slowly) : 
- These modes have been implemented, see flibit's post for details : https://plus.google.com/+flibitijibibo/posts/Kjuq7Dkg98c
- I'm removing letterboxing entirely and fixing aspect ratio/scaling/UI positioning problems everywhere, because there's no good reason... some levels will appear to "end" when they shouldn't with no black bars, but I think it's worth it. This means the game supports ultra-high monitors as well as ultra-wide.

Currently to-do for the UI fixup : 
- Cutscenes
- World map

Once I push these changes it'd be super nice to have a game-wide test pass with a very wide (like 21:9) and very high (like 4:3 or 5:4) resolution, so we can see if there's more things we can fix. Soon!

**Comment by renaudbedard** [comment]
World map and cutscenes are mostly good, first pass is done. I'll push this shortly!
