### ISSUE TITLE
Game crashed. My theory is that 2 textboxes wrer triggered at the same time.

### ISSUE THREAD

**Issue by Gyoo** [renaudbedard/fez-1.12-issues#163]
Context : I just got 32 cubes. To anticipate Dot's dialogue I mashed B early and it triggered a dialogue with an NPC. Game crashed during this dialogue, and I assume the game tried to have Dot's dialogue "at the same time"

Video : https://www.twitch.tv/gyoo_/v/97119326

Logs :
[[2016-10-25] Debug Log #3.txt](https://github.com/renaudbedard/fez-1.12-issues/files/551625/2016-10-25.Debug.Log.3.txt)

**Comment by flibitijibibo** [comment]
According to the log it crashed because the text had an invalid character... I wonder what that character was?

A Quick Fix(TM) for this crash would be for us to set a DefaultCharacter for the fonts, but I'm genuinely curious as to what string has the invalid character, or if it was just trashed memory getting sent to MeasureString.

**Comment by Gyoo** [comment]
So maybe this specific NPC has a character that became invalid for some reason ?

**Comment by renaudbedard** [comment]
I think what the problem is here, is that DOT speaks in Zuish in the ZU village... She shouldn't. I'll test that.

**Comment by renaudbedard** [comment]
Fixed! Will update asap.
