### ISSUE TITLE
SoundManager track loading error on macOS

### ISSUE THREAD

**Issue by lczyk** [renaudbedard/fez-1.12-issues#179]
Fresh install of macOS, Steam and then FEZ. Something is up with the SoundManager loading the sounds.

This is just a speculation based on the Debug Log, but I believe what might be happening is that when the SoundManger skips the loaded tracks, the dictionary keys for accessing them get messed up and the game exits when it tries to play `singles\fez` (which is indeed exactly when my game stops - milliseconds after starting to display the `FEZ` logo in the startup sequence)

[[2017-07-20] Debug Log #3.txt](https://github.com/renaudbedard/fez-1.12-issues/files/1164804/2017-07-20.Debug.Log.3.txt)

**Comment by flibitijibibo** [comment]
Does this happen with singlethreaded mode turned on?

**Comment by renaudbedard** [comment]
It looks like it's trying to preload audio tracks but can't parse the names right... all the attempts at loading them are with empty names. I'm also curious about if it's a threading problem, but it could be data corruption or some region/locale problem as well... is your OS in a non-english language?

**Comment by lczyk** [comment]
This indeed happens in single threaded mode too: [[2017-07-21] Debug Log #3.txt](https://github.com/renaudbedard/fez-1.12-issues/files/1167196/2017-07-21.Debug.Log.3.txt)

My system is, and has always been in en-UK language.

**Comment by lczyk** [comment]
Also; just for completeness, here is my [Settings.txt](https://github.com/renaudbedard/fez-1.12-issues/files/1167204/Settings.txt) (I've added the `.txt` extension for easy upload). The bug also happens at different screen resolutions and independently of the highDPI mode being on or off.

**Comment by renaudbedard** [comment]
I'd be curious to see if your Music.pak file is corrupted...

Here are the hashes for that file :
CRC32: F3DF48D4
MD5: 99B79E839D3355FB128EACD6D2E9B35C
SHA-1: A95C582EF2F32DDF3CC55E7C0CF9F267DA4E18CB

Can you find a way to verify the integrity of the Music.pak file and report
back?
It's located in the Content folder.

Thanks!

Edit : To clarify what I'm seeing in the debug log... the sound manager is able to load up to the "cycle\locrian_bass_4bars" music track, and then appears to fail loading the next track and is unable to recover. Then the game crashes when trying to play the title track. (arguably it could silently fail here instead of crashing...)

**Comment by lczyk** [comment]
Yeah, it does not look correct. The hashes I got (using bash) are:

MD5: 38cbcf2e6c9ad076cdced35ab0e634cf
SHA-1: ac6f6130751839e07c73da94ee17a68fc3c77326

Should I try to uninstall, and reinstall FEZ?

**Comment by flibitijibibo** [comment]
I would reinstall entirely, just in case some other files aren't valid... I'm surprised Steam doesn't throw an error when trying to verify the game cache, does it say files are invalid if you do it by hand?

https://support.steampowered.com/kb_article.php?ref=2037-QEUH-3335

**Comment by lczyk** [comment]
I've verified the game files as instructed (the verification worked only when I've started steam in online mode btw), and Steam found two corrupted files. They then got updated and the game works! Thank you. :)
