### ISSUE TITLE
Camera doesn't track Gomez when landing on moving platform

### ISSUE THREAD

**Issue by MistahKurtz** [renaudbedard/fez-1.12-issues#24]
If Gomez jumps on a platform that's moving up and down, such as the tower just outside of Villageville, if you do a perspective shift right as you land on the platform, sometimes the camera gets confused and doesn't track Gomez until it finishes rotating. It's only a small number of frames where this can happen.

http://imgur.com/TLojou0

I've noticed this happen in one or two other places on 1.11 as well, but can't remember specifics right now.

I'm guessing what happens is that the game doesn't expect Gomez to actually be on the platform yet, i.e., it hasn't taken the ground's movement into consideration when determining where to put the camera. You can compare the above example to what happens if Gomez actually _hasn't_ touched the ground yet: the camera goes to the same place.

http://imgur.com/EGUJtEp

**Comment by MistahKurtz** [comment]
Whoops, looks like this can either happen: 1.) When jumping from a moving platform to a static platform, or 2.) only any platform (probably not).

http://imgur.com/yTxt2pN

**Comment by renaudbedard** [comment]
Fixed! This is a one-frame issue, only happens if you rotate on the same frame that the physics engine detects that you've landed. The camera follow code happens after the rotation detection code, so it didn't have time to adapt to your new ground location as you landed. I force a "follow player" routine before any rotation, cheap fix but it seems to work.
