### ISSUE TITLE
Grabbing properties for ladders

### ISSUE THREAD

**Issue by MistahKurtz** [renaudbedard/fez-1.12-issues#25]
Both of these gameplay issues existed in 1.11, so I'm not sure how reasonable they would be to fix. Regardless...

1.) If you do a short hop while on a ladder, you actually can't grab the ladder until you fall a certain distance. Not sure if this has to do with distance or time.

http://imgur.com/z09q0hL

2.) There are "dead zones" on some ladders where you can't grab it. This ladder in particular probably has to do with the rotating platforms, but it's unfortunate since the player is affected when they do four default big jumps.

http://imgur.com/0YkQyOE

**Comment by renaudbedard** [comment]
Pretty sure this is all timing related. 
There's a timer in the ladder grab/release code that check when was the last time you grabbed a ladder and prevents you from re-grabbing it, so that you can hold up after jumping off a ladder and not re-grab it instantly. Looks like either this timer it too long, or the logic needs to change so that it feels more natural in the cases you describe...

**Comment by renaudbedard** [comment]
I'll transfer changes from the new vine grab code, pretty sure it's all the same problems. (#21)

**Comment by renaudbedard** [comment]
Fixed!
