### ISSUE TITLE
Switching language during dialogs

### ISSUE THREAD

**Issue by Gimlao** [renaudbedard/fez-1.12-issues#44]
If a dialog begin in english, after pausing / switching to another language / resuming the game, the dialog will still be in english, or any other language choosen when that dialog first started.

**Comment by renaudbedard** [comment]
I thought I might be able to address this from the speech bubble code, but since text is resolved from a tag to actual text before it gets into that system, I can't do dynamic translation. I only have the translated text from the caller, not the tag... and changing it everywhere is not feasible. Sorry, I'll have to pass on that one!
