### ISSUE TITLE
Doors' opening animation

### ISSUE THREAD

**Issue by Gimlao** [renaudbedard/fez-1.12-issues#5]
Some doors will have some parts disapearing during their opening animation.

**Comment by renaudbedard** [comment]
(oops, thought I had written a response here?)

This has been happening since 1.00 release (and all versions of the game on all platforms) because doors in the game have different ways of being built depending on when they were built... Phil did not transition all doors to the new system and making sure they're all perfect would be a lot of work, and risky work since changing level triles can have effect on collision and can make levels "implode" because we have Amazing Homemade Tools.

Sorry!
