### ISSUE TITLE
cube duplication while dying

### ISSUE THREAD

**Issue by Thejuikuen** [renaudbedard/fez-1.12-issues#57]
After grabbing my 8th bit I fell off a platform into the abyss. As I was falling, before gomez died, the cube collection animation played, I was credited for collecting the cube, then gomez died and respawned on the last ledge he touched. The golden cube from the 8 bit collection animation was left behind though and I was able to collect it as an extra cube.

I have tried replicating this, but it is difficult.

**Comment by flibitijibibo** [comment]
I wonder if this is along the lines of the dialog cube oddity from #49... we may just have to be more strict about what's allowed when starting the animation.

For now this is low-priority, but unlike 49 this may need fixing since it allows duplication.

**Comment by flibitijibibo** [comment]
I think this will be fixed in the next update.

What makes the bug weird is that the cube count increment and the cube deletion happen in the same function, so the conditions for adding the cube and NOT deleting it are extremely slim. That said, I noticed some potential cases for uninitialized memory as well as a _very_ slim case for the 8-bit cube and other treasures colliding, so I've patched those up. For this particular scenario I'm not sure why the cube would leak, but the next update will be MUCH more explicit about deleting the forced cube, so I don't expect this to happen again.
