### ISSUE TITLE
Gomez clipping into wall

### ISSUE THREAD

**Issue by Thejuikuen** [renaudbedard/fez-1.12-issues#60]
I'm not sure if you really care about small stuff like this, but I'll post it anyway 

![3](https://cloud.githubusercontent.com/assets/16115136/11767455/c13e342a-a173-11e5-8eef-cfc77670671e.png)

**Comment by Gyoo** [comment]
Anything special you need to do to reproduce that clip ?

**Comment by Thejuikuen** [comment]
Rotate the camera and walk forward

**Comment by renaudbedard** [comment]
I considered fixing those but it's a lot of editor work, I can't just make the asset collideable because it's not a trile, it's an art object... and they don't support collision.
Changing level collision is a risky ordeal and that particular kind of pillar is used a lot in the ZU area, I don't think I can take on this task for 1.12.

Cheers for reporting it though!
