### ISSUE TITLE
Lava_fork : Gomez can fall off the tuning fork while doing the controller code

### ISSUE THREAD

**Issue by Gyoo** [renaudbedard/fez-1.12-issues#71]
If you're on the platform just under the fork, and start doing the code, when Gomez is behind the fork he falls : https://www.gfycat.com/ScornfulCharmingDotterel

**Comment by renaudbedard** [comment]
This felt like a glitch that would cause actual problems when running the game (and playing it) so I went ahead and fixed it.

For the record : the "background" mode collision (when Gomez is silhouetted behind geometry) had a special case where the only ground that was taken into account for vertical collision was the ground that's directly under Gomez. This made sure that you wouldn't fall if you get sandwiched between two walls like in this level : 

![wall_hole](https://cloud.githubusercontent.com/assets/251134/17162909/1c6a33d2-5388-11e6-98f5-c245685923c5.gif)

But doing it this way made some decoration tiles (like the metallic border around platforms in LAVA levels) fall-through in background mode; I added a fallback check to the collision so that if no collision is detected, the regular "walk until you hit a thing" collision traversal happens. Seems to work!
