### ISSUE TITLE
Sewer_Geyser : Geyser platforms remanence when going to a menu

### ISSUE THREAD

**Issue by Gyoo** [renaudbedard/fez-1.12-issues#72]
I think the video will be enough to explain : https://www.gfycat.com/LawfulAmusedKilldeer

**Comment by Gyoo** [comment]
Btw, it can happen in every place where there are such platforms

**Comment by Gyoo** [comment]
Does it also seem to happen with spinning cubes ? http://i.imgur.com/hm3mw9G.png

**Comment by Thejuikuen** [comment]
I don't think you can land on those though? It's just a graphical glitch.

**Comment by Gyoo** [comment]
Yes, it's just graphical

**Comment by flibitijibibo** [comment]
I think I've diagnosed this... this is a really old bug, I think! Possibly as old as the 360 version...?

When we leave the map state, the map makes some calls to the camera manager which involves rebuilding the world view/projection. The engine has a system that lets other components know when the view and projection change, and one of these components is the system that culls out level data.

For whatever reason, the specific type of culling applied adds extra instance data to the buffer that draws out elements like the geyser platforms and cubits, which is where these ghost objects come from. It's just random vertex data with no game logic attached!

But, the type of culling _seems_ to be an attempt at optimizing a different type of culling mode in the engine ("Partial" rather than "Full"). Forcibly setting the cull type to the slower(?) mode resolves this issue. If we can figure out why the partial mode _adds_ instance data and prevent that, this should be resolved while having both cull modes.

**Comment by flibitijibibo** [comment]
Consulted with Renaud and I've fixed this issue for the map, should be in the next update.

**Comment by renaudbedard** [comment]
\o/
