### ISSUE TITLE
4 Side puzzle skip

### ISSUE THREAD

**Issue by Thejuikuen** [renaudbedard/fez-1.12-issues#74]
https://gfycat.com/ImpurePertinentComet

When the concrete cube spawns, you can pass through the door by holding up.

**Comment by flibitijibibo** [comment]
This should be fixed in the next update.

I actually added a rule disallowing the entering of this specific door based on puzzle status, but I wonder if there just needs to be a general rule disallowing door volumes that are still 'closed'... surely this exists in at least one other place. For now, :shrug:
