### ISSUE TITLE
Adding more save slots

### ISSUE THREAD

**Issue by Gyoo** [renaudbedard/fez-1.12-issues#85]
This is more a feature request than an issue, and it will be followed by a second one with another idea.

Currently, the game supports 3 save slots. As I understand it is largely sufficient for casual gameplay, for us speedrunners it's quite a pain if we want to train specific parts of the game.
- I always keep a slot for my 209.4% casual save, because that's where everything started (^^')
- I have a slot for speedrun attempts.
- So that gives me only one more slot to have a save at a specific spot.

The solution that I found was to keep savefiles in a backup folder that I placed in the %appdata% folder of the game, but it's quite a hassle to change it everytime I need something. Also, since the game saves litterally everytime you cross a door, if I want to grind a room several times I need to at least copy the save, or reimport it.

I would totally understand if you don't want to change that, but at least I expressed my opinion about it :P

**Comment by flibitijibibo** [comment]
This probably won't happen because the slot limit is littered around and it'd be difficult to get this into the UI properly. That said, an external save management tool would probably be WAY better than what we'd end up writing into the engine.

Some info on how saves work: The save management screen loads the save info right as you enter the management menu, so you can actually drop savedata into the folder during gameplay without any trouble. Of course, you would need to place it in a new slot, but this can still work for grinding purposes.

A handy speedrun training tool would be a save manager that lets you list your saves from a user folder, which can be for whatever you want, and with whatever metadata you want (descriptions, probably), and you can tell it to copy the save selected into the SaveSlotx location. It can automatically alternate between slots 2 and 3, and whenever you want to reload, you can mash copy from the tool and then switch slots in-game. This would effectively give you infinite slots with the exact save system we have today.

Odds are you could write this with a drag-and-drop GUI maker and get exactly what you need in an afternoon.
